### ISSUE TITLE
Exception loading protection file

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#130]
From dedicated server.

Provided by: http://steamcommunity.com/id/Rioclaw
Described here: http://steamcommunity.com/sharedfiles/filedetails/?id=316190120&tscn=1447590652

Log details:
http://pastebin.com/49ibXKfZ
```
2015-11-15 02:08:08.650 - Thread:   1 ->     Registered modules from: Sandbox.Graphics, Version=0.1.5795.28249, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:08.654 - Thread:   1 ->     Registered modules from: Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:08.655 - Thread:   1 ->     Registered modules from: SpaceEngineers.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:08.688 - Thread:   1 ->     Registered modules from: Sandbox.Game, Version=0.1.5795.28250, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:09.039 - Thread:   1 ->     GC Memory: 80,542,872 B
2015-11-15 02:08:09.041 - Thread:   1 ->     Process Memory: 527,556,608 B
2015-11-15 02:08:12.790 - Thread:   1 ->     Skip Procedural World Generator
2015-11-15 02:08:12.809 - Thread:   1 ->     MyLights.LoadData() - START
2015-11-15 02:08:12.815 - Thread:   1 ->     MyLights.LoadData() - END
2015-11-15 02:08:12.861 - Thread:   1 ->     MySunWind.LoadData() - START
2015-11-15 02:08:12.862 - Thread:   1 ->     MySunWind.LoadData() - END
2015-11-15 02:08:12.894 - Thread:   1 ->     MyParticlesLibrary.ctor - START
2015-11-15 02:08:13.101 - Thread:   1 ->     MyParticlesLibrary.ctor - END
2015-11-15 02:08:13.123 - Thread:   1 ->     MyMissiles.LoadContent() - START
2015-11-15 02:08:13.123 - Thread:   1 ->     MyMissiles.LoadContent() - END
2015-11-15 02:08:13.124 - Thread:   1 ->     MyExplosions.LoadData() - START
2015-11-15 02:08:13.139 - Thread:   1 ->     MyExplosions.LoadData() - END
2015-11-15 02:08:13.162 - Thread:   1 ->     Pre-loading neutral ship spawn groups...
2015-11-15 02:08:13.162 - Thread:   1 ->     End pre-loading neutral ship spawn groups.
2015-11-15 02:08:13.236 - Thread:   1 ->     MyScriptManager.LoadData() - START
2015-11-15 02:08:17.799 - Thread:   1 ->        Registered modules from: _StatLogic, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Script loaded: _StatLogic, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Registered modules from: 484504816, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Script loaded: 484504816, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Registered modules from: 403904197.sbm_midspace, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Script loaded: 403904197.sbm_midspace, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Registered modules from: 442436541, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Script loaded: 442436541, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Registered modules from: 442436465, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Script loaded: 442436465, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Registered modules from: 442436391, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Script loaded: 442436391, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Registered modules from: 402858936, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.800 - Thread:   1 ->        Script loaded: 402858936, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.801 - Thread:   1 ->        Registered modules from: 364731781.sbm_midspace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.801 - Thread:   1 ->        Script loaded: 364731781.sbm_midspace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.801 - Thread:   1 ->        Registered modules from: 316190120.sbm_midspace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.803 - Thread:   1 ->        Script loaded: 316190120.sbm_midspace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2015-11-15 02:08:17.803 - Thread:   1 ->     MyScriptManager.LoadData() - END
2015-11-15 02:08:18.048 - Thread:   1 ->     Loading voxel storage from file 'C:\Users\HTPC\AppData\Roaming\SpaceEngineersDedicated\Saves\MHP\EarthLike-1360562010d120000.vx2'
2015-11-15 02:08:22.234 - Thread:   1 ->     Loading voxel storage from file 'C:\Users\HTPC\AppData\Roaming\SpaceEngineersDedicated\Saves\MHP\Moon-34472925d19000.vx2'
2015-11-15 02:08:24.531 - Thread:   1 ->     Loading voxel storage from file 'C:\Users\HTPC\AppData\Roaming\SpaceEngineersDedicated\Saves\MHP\Alien-1962799658d120000.vx2'
2015-11-15 02:08:26.881 - Thread:   1 ->     Loading voxel storage from file 'C:\Users\HTPC\AppData\Roaming\SpaceEngineersDedicated\Saves\MHP\Titan-199653917d19000.vx2'
2015-11-15 02:08:29.606 - Thread:   1 ->     Loading voxel storage from file 'C:\Users\HTPC\AppData\Roaming\SpaceEngineersDedicated\Saves\MHP\Mars-1288225932d120000.vx2'
2015-11-15 02:08:32.440 - Thread:   1 ->     Loading voxel storage from file 'C:\Users\HTPC\AppData\Roaming\SpaceEngineersDedicated\Saves\MHP\Europa-42756455d19000.vx2'
2015-11-15 02:08:40.919 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/UraniumOreToIngot was not found.
2015-11-15 02:08:40.919 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/SiliconOreToIngot was not found.
2015-11-15 02:08:40.919 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/StoneOreToIngot was not found.
2015-11-15 02:08:40.919 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/CobaltOreToIngot was not found.
2015-11-15 02:08:40.922 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/ReactorComponent was not found.
2015-11-15 02:08:41.575 - Thread:   1 ->     No blueprint that produces a single result with Id 'MyObjectBuilder_BlueprintDefinition/BulletproofGlass'
2015-11-15 02:08:42.701 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/StoneOreToIngot was not found.
2015-11-15 02:08:42.701 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/IronOreToIngot was not found.
2015-11-15 02:08:44.112 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/Missile200mm was not found.
2015-11-15 02:08:44.355 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/ShieldPoints was not found.
2015-11-15 02:08:46.257 - Thread:   1 ->     Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/HandDrill was not found.
2015-11-15 02:08:46.421 - Thread:   1 ->     Checkpoint.CameraAttachedTo: 0
2015-11-15 02:08:46.422 - Thread:   1 ->     ERROR: Camera entity from checkpoint does not exists!
2015-11-15 02:08:46.426 - Thread:   1 ->     CameraAttachedTo: Spectator
2015-11-15 02:08:46.551 - Thread:   1 ->     MySession.LogSettings - START
2015-11-15 02:08:46.552 - Thread:   1 ->        Name = MHV4
2015-11-15 02:08:46.552 - Thread:   1 ->        Description = 
2015-11-15 02:08:46.552 - Thread:   1 ->        GameDateTime = 01/02/2081 03:23:09
2015-11-15 02:08:46.552 - Thread:   1 ->        Password = 
2015-11-15 02:08:46.552 - Thread:   1 ->        CurrentPath = C:\Users\HTPC\AppData\Roaming\SpaceEngineersDedicated\Saves\MHP
2015-11-15 02:08:46.560 - Thread:   1 ->        WorkshopId = 
2015-11-15 02:08:46.560 - Thread:   1 ->        CameraController = Sandbox.Engine.Utils.MySpectatorCameraController
2015-11-15 02:08:46.560 - Thread:   1 ->        ThumbPath = C:\Users\HTPC\AppData\Roaming\SpaceEngineersDedicated\Saves\MHP\thumb.jpg
2015-11-15 02:08:46.567 - Thread:   1 ->        Settings:
2015-11-15 02:08:46.568 - Thread:   1 ->           GameMode = Survival
2015-11-15 02:08:46.568 - Thread:   1 ->           MaxPlayers = 20
2015-11-15 02:08:46.568 - Thread:   1 ->           OnlineMode = PUBLIC
2015-11-15 02:08:46.568 - Thread:   1 ->           AutoHealing = False
2015-11-15 02:08:46.568 - Thread:   1 ->           WeaponsEnabled = True
2015-11-15 02:08:46.568 - Thread:   1 ->           ThrusterDamage = True
2015-11-15 02:08:46.568 - Thread:   1 ->           EnableSpectator = False
2015-11-15 02:08:46.568 - Thread:   1 ->           EnableCopyPaste = False
2015-11-15 02:08:46.568 - Thread:   1 ->           MaxFloatingObjects = 32
2015-11-15 02:08:46.568 - Thread:   1 ->           CargoShipsEnabled = False
2015-11-15 02:08:46.568 - Thread:   1 ->           EnvironmentHostility = SAFE
2015-11-15 02:08:46.568 - Thread:   1 ->           ShowPlayerNamesOnHud = True
2015-11-15 02:08:46.568 - Thread:   1 ->           InventorySizeMultiplier = 3
2015-11-15 02:08:46.568 - Thread:   1 ->           RefinerySpeedMultiplier = 3
2015-11-15 02:08:46.568 - Thread:   1 ->           AssemblerSpeedMultiplier = 3
2015-11-15 02:08:46.568 - Thread:   1 ->           AssemblerEfficiencyMultiplier = 1
2015-11-15 02:08:46.568 - Thread:   1 ->           WelderSpeedMultiplier = 2
2015-11-15 02:08:46.568 - Thread:   1 ->           GrinderSpeedMultiplier = 2
2015-11-15 02:08:46.568 - Thread:   1 ->           ClientCanSave = False
2015-11-15 02:08:46.568 - Thread:   1 ->           HackSpeedMultiplier = 0.33
2015-11-15 02:08:46.568 - Thread:   1 ->           PermanentDeath = True
2015-11-15 02:08:46.568 - Thread:   1 ->           DestructibleBlocks =  True
2015-11-15 02:08:46.568 - Thread:   1 ->           EnableScripts =  True
2015-11-15 02:08:46.568 - Thread:   1 ->           AutoSaveInMinutes = 15
2015-11-15 02:08:46.568 - Thread:   1 ->           SpawnShipTimeMultiplier = 0.5
2015-11-15 02:08:46.568 - Thread:   1 ->           ProceduralDensity = 0
2015-11-15 02:08:46.568 - Thread:   1 ->           ProceduralSeed = 0
2015-11-15 02:08:46.568 - Thread:   1 ->           DestructibleBlocks = True
2015-11-15 02:08:46.568 - Thread:   1 ->           EnableIngameScripts = True
2015-11-15 02:08:46.568 - Thread:   1 ->           ViewDistance = 15000
2015-11-15 02:08:46.568 - Thread:   1 ->           Battle = False
2015-11-15 02:08:46.568 - Thread:   1 ->           Voxel destruction = True
2015-11-15 02:08:46.568 - Thread:   1 ->     MySession.LogSettings - END
2015-11-15 02:08:46.628 - Thread:   1 ->     Session loaded
2015-11-15 02:08:46.662 - Thread:   1 ->  MySandboxGame.Initialize() - END
2015-11-15 02:08:46.664 - Thread:   1 ->  Timer Frequency: 2942861
2015-11-15 02:08:46.664 - Thread:   1 ->  Ticks per frame: 49253
2015-11-15 02:08:46.779 - Thread:   1 ->  Updating continues.
2015-11-15 02:08:49.774 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at midspace.adminscripts.Protection.ProtectionConfig.Load()
   at midspace.adminscripts.ChatCommandLogic.InitServer()
   at midspace.adminscripts.ChatCommandLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass2.<Run>b__1()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run[T](String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2015-11-15 02:08:49.776 - Thread:   1 ->  Hiding window
2015-11-15 02:08:50.024 - Thread:   1 ->  Network readers disposed
2015-11-15 02:08:50.029 - Thread:   1 ->  Logging off Steam...
2015-11-15 02:08:50.032 - Thread:   1 ->  Shutting down server...
2015-11-15 02:08:50.348 - Thread:   1 ->  Done
2015-11-15 02:08:50.391 - Thread:   1 ->  Hiding window done
2015-11-15 02:08:50.391 - Thread:   1 ->  Showing message
2015-11-15 02:08:50.510 - Thread:   1 ->  ERROR: branch name cannot be resolved, services=
2015-11-15 02:08:50.511 - Thread:   1 ->  ERROR: branch name cannot be resolved, services=
2015-11-15 02:08:50.511 - Thread:   1 ->  ERROR: branch name cannot be resolved, services=
```

**Comment by Spcemarine** [comment]
Serialization probably returned `null`. It's not an issue that'd happen if you do not touch the files...
