### ISSUE TITLE
New bug/conflict issue with SE

### ISSUE THREAD

**Issue by EngineerBean** [midspace/Space-Engineers-Admin-script-mod#142]
2016-01-08 18:12:05.943 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at midspace.adminscripts.Protection.GameLogicComponents.ProtectedCubePlacer.UpdateBeforeSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass2.<Run>b__1()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.RunInternal(String[] args)
   at SpaceEngineers.MyProgram.Main(String[] args)

**Comment by midspace** [comment]
This seems to agree with this issue posted here:
http://forum.keenswh.com/threads/01-116-ds-client-crash-when-selecting-any-block.7377855/

Only details, is that it is occurring on a dedicated server.
Do we have anything else to go on?

**Comment by midspace** [comment]
Here is a copy of the log in the thread.
I haven't been able to reproduce the issue as yet.
I have a dedicated server running with Protected area, and I have added all mods specified in the log, in the order specified in the log.
I have even removed my Admin status, and it still isn't giving me any exception.

http://pastebin.com/P4pQbwnB

**Comment by midspace** [comment]
At the moment, I'm guessing the player might be trying to place a block before permissions and protection zones has downloaded?
SpaceMarine?

**Comment by Spcemarine** [comment]
Yes, that'd be possible but still it is extremely weird that the permissions are not downloaded yet after about 30 seconds.

**Comment by Spcemarine** [comment]
Lets leave this open until we have evidence that the bug is fixed.

**Comment by midspace** [comment]
I'm wondering if we should have a null check? `ProtectionHandler.Config != null`

**Comment by Spcemarine** [comment]
`!ChatCommandLogic.Instance.AllowBuilding` in line 45 is only set to `true` after the client received the config from the server. If it is still `null` we'll have to find out why. I think this approach allows us to track down the bug properly.

**Comment by EngineerBean** [comment]
Please forgive me for not including more information. This exception occured when selecting a block off toolbar on a dedicated server.

**Comment by midspace** [comment]
Has this issue been resolved?
I have heard no further replies that it is still a problem.

**Comment by midspace** [comment]
Closing issue.
`/savetoolbar` has been removed, as it is now supported in game.
We haven't heard of any further issues with this bug.
