### ISSUE TITLE
Admin Server Error

### ISSUE THREAD

**Issue by cobaltsieg** [midspace/Space-Engineers-Admin-script-mod#175]
Since a recent personal server power loss and backup restore, attempting to load my dedicated server fails. Upon testing of individual mods, and log checks, I have isolated this mod as the reason the server fails to run. 

Any assistance would be deeply appreciated.

The log information before the crash is as follows:

"2017-01-07 13:45:32.787 - Thread:   1 ->  ##Mod## Admin Helper Server Initialisation
2017-01-07 13:45:32.925 - Thread:   1 ->  Exception occured: System.InvalidOperationException: There is an error in XML document (1, 1). ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read5_ArrayOfPrivateConversation()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at Sandbox.ModAPI.MyAPIUtilities.VRage.Game.ModAPI.IMyUtilities.SerializeFromXML[T](String xml)
   at midspace.adminscripts.Config.Files.PrivateMessageLogFile.Load()
   at midspace.adminscripts.ServerConfig..ctor(List`1 commands)
   at midspace.adminscripts.ChatCommandLogic.InitServer()
   at midspace.adminscripts.ChatCommandLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run[T](String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2017-01-07 13:45:32.925 - Thread:   1 ->  InnerException: 
2017-01-07 13:45:32.925 - Thread:   1 ->  Exception occured: System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read5_ArrayOfPrivateConversation()
2017-01-07 13:45:32.926 - Thread:   1 ->  Hiding window
2017-01-07 13:45:33.133 - Thread:   1 ->  Network readers disposed
2017-01-07 13:45:33.136 - Thread:   1 ->  Logging off Steam...
2017-01-07 13:45:33.136 - Thread:   1 ->  Shutting down server...
2017-01-07 13:45:33.224 - Thread:   1 ->  Done
2017-01-07 13:45:33.844 - Thread:   1 ->  Hiding window done
2017-01-07 13:45:33.844 - Thread:   1 ->  Showing message
2017-01-07 13:45:33.860 - Thread:   1 ->  ERROR: branch name cannot be resolved, services=
2017-01-07 13:45:33.860 - Thread:   1 ->  ERROR: branch name cannot be resolved, services=
2017-01-07 13:45:33.860 - Thread:   1 ->  ERROR: branch name cannot be resolved, services="

**Comment by midspace** [comment]
The private chat message log file has become corrupted.
It stores all the chat messages sent by players, allowing them to view old messages. Especially to players who have been offline, or just joined and want to know what was in a conversation. 

More than likely the file is not recoverable.
You will have to delete it before restarting the server.

You can find the location of the file described here:
https://github.com/midspace/Space-Engineers-Admin-script-mod/wiki/Message-of-the-day-(motd)-&-server-configuration

The file will be of the name: "PrivateMessageLog_{0}.xml"
Where {0} is the world name.

**Comment by cobaltsieg** [comment]
Thank you so very much. I've been working so hard on trying to get my
server back to normal. This helps enormously.

**Comment by midspace** [comment]
We've had another repeat of this issue recently.
I'm still not sure what is causing this.
I've only got a few theories.
1. Save is been called twice almost simultaneously. Shouldn't happen, because the file I/O should prevent shared access to the file.
2. Save is been aborted mid way as the game closes/exits. Shouldn't happen, as it should be in a blocking call. Ie., game cannot proceed until this save is complete.

```
2017-07-23 14:35:40.281 - Thread:   1 ->  ##Mod## Admin Helper Server Initialisation
2017-07-23 14:35:54.830 - Thread:   1 ->  Exception occured: System.Exception: An error occuring loading the file 'PrivateMessageLog_Star System 2017-07-21 15-15.xml'. Begining with the text "                                                                                                    ". ---> System.InvalidOperationException: There is an error in XML document (1, 1). ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
```
[syfUkda3.txt](https://github.com/midspace/Space-Engineers-Admin-script-mod/files/1169521/syfUkda3.txt)

**Comment by midspace** [comment]
I haven't heard any more reports of this issue.
I'm hoping we've nailed this one.
