### ISSUE TITLE
Error at dedicated Server startup

### ISSUE THREAD

**Issue by HaxXorHardy** [midspace/Space-Engineers-Admin-script-mod#193]
Hi, I have an issue while booting the server.
`
2018-03-13 05:29:30.734 - Thread:   1 ->  ##Mod## Admin Helper Server Initialisation
2018-03-13 05:29:30.792 - Thread:   1 ->  Exception during DS config load: System.InvalidOperationException: There is an error in XML document (72, 10). ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read9_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read10_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read11_MyConfigDedicated()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Sandbox.Engine.Utils.MyConfigDedicated`1.Load(String path)
2018-03-13 05:29:30.861 - Thread:   1 ->  Exception during DS config load: System.InvalidOperationException: There is an error in XML document (72, 10). ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read9_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read10_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read11_MyConfigDedicated()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Sandbox.Engine.Utils.MyConfigDedicated`1.Load(String path)
2018-03-13 05:29:30.862 - Thread:   1 ->  Exception during DS config load: System.InvalidOperationException: There is an error in XML document (72, 10). ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read9_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read10_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyConfigDedicatedData1.Read11_MyConfigDedicated()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Sandbox.Engine.Utils.MyConfigDedicated`1.Load(String path)
`

**Comment by midspace** [comment]
Hi,
Are you able to provide a copy of the save files and the configuration files in the Storage folder?

**Comment by HaxXorHardy** [comment]
Here are the server files:
[Space.zip](https://github.com/midspace/Space-Engineers-Admin-script-mod/files/1808216/Space.zip)

**Comment by midspace** [comment]
It appears you haven't run the DS Configurator in a very long time. The Configuration file `SpaceEngineers-Dedicated.cfg` it uses as a result is out of date.
It has a lot of of settings when my Admin Mod loads, including the list of Administrators.
This causes the error during load which you see.

I've attempted to update the file for you, so it should be a matter of simply replacing it on the server.
[SpaceEngineers-Dedicated.zip](https://github.com/midspace/Space-Engineers-Admin-script-mod/files/1810073/SpaceEngineers-Dedicated.zip)

**Comment by HaxXorHardy** [comment]
thank you this worked for me!!! <3
