### ISSUE TITLE
Server exception due to SendChatHistory

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#63]
Issue reported by user
http://steamcommunity.com/profiles/76561198019431686

Crashed the user's server.

```
Parameter name: index
   at midspace.adminscripts.ServerConfig.SendChatHistory(UInt64 receiver, UInt32 entryCount)
   at midspace.adminscripts.ConnectionHelper.ProcessServerData(String dataString)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayerSyncObject.ModMessageRecieved(CustomModMsg& msg, MyNetworkClient sender)
   at Sandbox.Game.Multiplayer.MySyncLayer.MyCallbackBase`1.Handle(TMsg& msg, UInt64 sender, TimeSpan timestamp)
   at Sandbox.Game.Multiplayer.MySyncLayer.MyCallbackBase`1.Sandbox.Engine.Multiplayer.ITransportCallback.Receive(ByteStream source, UInt64 sender, TimeSpan timestamp)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(Byte[] data, Int32 dataSize, UInt64 sender, TimeSpan timestamp)
   at Sandbox.Engine.Networking.MyReceiveQueue.ProcessMessages(NetworkMessageDelegate handler, TimeSpan delay)
   at Sandbox.Engine.Networking.MyNetworkReader.Process(TimeSpan lag)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.FixedRenderLoop.<>c__DisplayClass2.<Run>b__1()
   at Sandbox.Engine.Platform.GenericRenderLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.FixedRenderLoop.Run(VoidAction tickCallback)
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at VRage.Dedicated.WindowsService.MainThreadStart(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
2015-07-07 03:40:33.472 - Thread:   5 ->  Hiding window
2015-07-07 03:40:33.693 - Thread:   5 ->  Network readers disposed
2015-07-07 03:40:33.693 - Thread:   5 ->  Logging off Steam...
2015-07-07 03:40:33.693 - Thread:   5 ->  Shutting down server...
```

**Comment by midspace** [comment]
I'm guessing at the moment, this is because cache is currently empty (0 items).
       List<ChatMessage> cache = new List<ChatMessage>(ChatMessages.OrderByDescending(m => m.Date));

So when it hits, it'll try retrieving a item at [0].
                ChatMessage chatMessage = cache[i];
