### ISSUE TITLE
Corrupt files loaded by host causes crash.

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#95]
Just logging this for posterity.

I'm wondering if we can wrapper the exception to provide more detailed exception and rethrow.
ie., the actual filename, and possibly the first 100 characters of the text.

```
2015-09-03 16:37:35.878 - Thread:   1 ->  Timer Frequency: 3906264
2015-09-03 16:37:35.878 - Thread:   1 ->  Ticks per frame: 65377
2015-09-03 16:37:35.931 - Thread:   1 ->  Updating continues.
2015-09-03 16:37:38.611 - Thread:   1 ->  Could not add item into production block's queue: Blueprint MyObjectBuilder_BlueprintDefinition/NATO_5p56x45mmMagazine was not found.
2015-09-03 16:37:42.418 - Thread:   1 ->  Exception occured: System.InvalidOperationException: There is an error in XML document (1, 1). ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read4_ArrayOfChatMessage()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at Sandbox.ModAPI.MyAPIUtilities.Sandbox.ModAPI.IMyUtilities.SerializeFromXML[T](String xml)
   at midspace.adminscripts.ServerConfig.LoadOrCreateChatLog()
   at midspace.adminscripts.ServerConfig..ctor(List`1 commands)
   at midspace.adminscripts.ChatCommandLogic.InitServer()
   at midspace.adminscripts.ChatCommandLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.FixedRenderLoop.<>c__DisplayClass2.<Run>b__1()
   at Sandbox.Engine.Platform.GenericRenderLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.FixedRenderLoop.Run(VoidAction tickCallback)
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run[T](String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2015-09-03 16:37:42.418 - Thread:   1 ->  InnerException: 
2015-09-03 16:37:42.418 - Thread:   1 ->  Exception occured: System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read4_ArrayOfChatMessage()
2015-09-03 16:37:42.419 - Thread:   1 ->  Hiding window
2015-09-03 16:37:42.628 - Thread:   1 ->  Network readers disposed
2015-09-03 16:37:42.628 - Thread:   1 ->  Logging off Steam...
2015-09-03 16:37:42.628 - Thread:   1 ->  Shutting down server...
2015-09-03 16:37:42.711 - Thread:   1 ->  Done
2015-09-03 16:37:42.714 - Thread:   1 ->  Hiding window done
2015-09-03 16:37:42.715 - Thread:   1 ->  Showing message
```

**Comment by Spcemarine** [comment]
Yes, that might be very useful. If possible, it might be better to locate the position of the xml error, in this case 1, 1 and display the text around it. Let's say about 5 lines or 50 characters, that would more than enough if it points to the actual error. Also in some cases where the error isn't located in the displayed section we won't get any useful information.
